#![forbid(unsafe_code)]

use std::sync::Arc;

use chrono::Utc;
use rhelma_event::{
    generate_event_id, purpose, EventBus, EventEnvelope, EventRequestContext, EventRequestFlags,
    EventSource, EventTraceContext, PolicyMeta, Residency,
};
use rhelma_event_kafka::{KafkaConfig, KafkaEventBus, KafkaProducerWrapper};
use serde_json::json;

fn kafka_cfg() -> KafkaConfig {
    // NOTE: Producer creation does not require a reachable broker; publish should fail-fast
    // on contract violations before attempting to send.
    KafkaConfig {
        brokers: "localhost:9092".into(),
        topic_prefix: "rhelma.".into(),
        group_id: "rhelma-event-kafka-test-group".into(),
        ..KafkaConfig::default()
    }
}

fn valid_env(topic: &str) -> EventEnvelope {
    let rid = generate_event_id();
    let cid = generate_event_id();

    EventEnvelope {
        event_id: generate_event_id(),
        event_version: 1,
        topic: topic.to_string(),
        key: None,

        timestamp: Utc::now(),
        published_at: Utc::now(),

        source: EventSource {
            service: "rhelma-event-kafka-test".into(),
            version: "0.0.0-test".into(),
            region: "eu".into(),
        },

        request: EventRequestContext {
            request_id: Some(rid),
            correlation_id: Some(cid),
            tenant_id: Some("t_test".into()),
            user_id: None,
            flags: EventRequestFlags::default(),
        },

        trace: EventTraceContext {
            trace_id: None, // will be generated by finalize_strict()
            span_id: None,  // will be generated by finalize_strict()
            tracestate: None,
            baggage: None,
            parent_span_id: None,
        },
        payload: json!({"hello": "world"}),
        payload_type: "application/json".into(),
        schema_ref: "rhelma.demo.test.v1".into(),

        policy: PolicyMeta::public(purpose::KAFKA),
        residency: Residency::Global,
        encryption: None,

        signature: None,
        hash: None,
    }
}

fn invalid_env_missing_schema() -> EventEnvelope {
    let mut e = valid_env("rhelma.demo.contract");
    // Contract violation: schema_ref must be present and non-empty.
    e.schema_ref = "".into();
    e
}

#[tokio::test]
async fn publish_contract_enforced_missing_schema_ref_fails_fast() {
    let cfg = kafka_cfg();
    let producer = Arc::new(KafkaProducerWrapper::new(cfg).expect("producer init"));
    let bus = KafkaEventBus::new(producer);

    let err = bus
        .publish(invalid_env_missing_schema())
        .await
        .expect_err("expected contract violation");

    let msg = err.to_string();
    assert!(
        msg.to_ascii_lowercase().contains("schema_ref"),
        "error should mention schema_ref, got: {msg}"
    );
}
